---

- name: "persist the GOROOT environment change"
  lineinfile:
    create: "yes"
    dest: "{{ golang_environment_file }}"
    line: "export GOROOT={{ golang_unarchive_dest }}/go"
    regexp: '^export GOROOT='
    state: "present"

- name: "persist the PATH environment change"
  lineinfile:
    create: "yes"
    dest: "{{ golang_environment_file }}"
    line: "export PATH=$PATH:$GOROOT/bin"
    regexp: '^export PATH='
    state: "present"
