---

- name: "Persist the GOROOT environment change"
  lineinfile:
    create: "yes"
    dest: "{{ golang_environment_file }}"
    line: "export GOROOT={{ golang_unarchive_dest }}/go"
    regexp: '^export GOROOT='
    state: "present"

- name: "Perisist the GOPATH environment change"
  lineinfile:
    create: "yes"
    dest: "{{ golang_environment_file }}"
    line: "export GOPATH={{ golang_gopath }}"
    regexp: '^export GOPATH='
    state: "present"

- name: "Persist the PATH environment change"
  lineinfile:
    create: "yes"
    dest: "{{ golang_environment_file }}"
    line: "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin"
    regexp: '^export PATH='
    state: "present"
